# Site settings
title: "JetBundle"
description: "Physics • Mathematics • Computation • Finance — Origins, Applications & Engineering"
url: "https://jetbundle.github.io"
baseurl: ""

# Useful links
github_username: "jetbundle"
facebook_username: ""
twitter_username: ""
linkedin_id: ""

# Theme
remote_theme: luxedo/jekyll-theme-potato-hacker
theme_repository: "https://github.com/luxedo/jekyll-theme-potato-hacker"
theme_base: "dark"
theme_switch: "on"

# Extra settings
blog: "on"
avatar: "on"
avatar_image: "assets/img/avatar.jpg"
avatar_description: "Physics • Mathematics • Computation • Finance — Origins, Applications & Engineering"

highlighter_theme: monokai

toolbar_priority:
  - Topics
  - About
  - Publications

# Collections
collections:
  dropdown:
    output: true
  items:
    output: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore

# PDF Settings
pdf_height: 900px

